version: "3.9"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noc_dashboard
    expose:
      - "8501"
    env_file:
      - .env

  capture:
    build:
      context: .
      dockerfile: Dockerfile.capture
    container_name: noc_capture
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: noc_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dashboard
  generator:
  build:
    context: .
    dockerfile: Dockerfile.capture
  container_name: noc_generator
  command: python src/data_generator.py